#!/bin/bash

BARE_REPOS_PATH='/repos/'
NONBARE_REPOS_PATH='/home/public_html/'

if [ $# -lt 1 ]
then
  echo "Usage: $0 Project"
  exit
fi

groupdel $1

pushd $BARE_REPOS_PATH > /dev/null
rm -rf $1

pushd $NONBARE_REPOS_PATH > /dev/null
rm -rf $1