#!/bin/bash

BARE_REPOS_PATH='/repos/'
NONBARE_REPOS_PATH='/home/public_html/'

if [ $# -lt 2 ]
then
  echo "Usage: $0 Project User1 User2 ..."
  exit
fi

groupadd $1

for user in $@; do
  if [ "$user" != $1 ]; then
    usermod -a -G $1 $user
  fi
done

usermod -a -G $1 'deploy'

pushd $BARE_REPOS_PATH > /dev/null
mkdir $1
pushd $1 > /dev/null
git init --bare --shared=0770

#  git --bare update-server-info
#  git config core.worktree /home/caius/vhosts/somesite.com/htdocs
#  git config core.bare false
#  git config receive.denycurrentbranch ignore
#  cat > hooks/post-receive
#  #!/bin/sh
#  git checkout -f
#  ^D

pushd .. > /dev/null
chown -R root:$1 $1

cp `dirname $0`/git-receive-hook "$BARE_REPOS_PATH$1/hooks/post-receive"
chmod +x "$BARE_REPOS_PATH$1/hooks/post-receive"

pushd $NONBARE_REPOS_PATH > /dev/null
git clone --no-hardlinks $BARE_REPOS_PATH$1
chown -R root:git $1
chmod -R 0775 $1